export const data = [
  {
    "id": 1,
    "name": "Recipe App",
    "image": "/../public/recipeApp.png",
    "description": "Full-stack MERN recipe CRUD app. Back-end is an express API to a MongoDB database with hundreds of recipes",
    "tags": ["express", "mongodb", "react", "react-query", "jest"],
    "source_code": "https://github.com/tylerFretz/recipe-app-js/",
    "demo": "https://fathomless-hamlet-32500.herokuapp.com/",
  },
  {
    "id": 2,
    "name": "Sorting Algorithms Visualizer",
    "image": "/../public/sortingApp.png",
    "description": "A visualization app for various sorting algorithms like merge sort, quick sort, insertion sort, bubble sort and selection sort",
    "tags": ["react", "node", "github-actions", "material-ui", "typescript"],
    "source_code": "https://github.com/tylerFretz/sorting-algorithms-visualizer/",
    "demo": "https://jovial-jang-92478f.netlify.app/",
  },
  {
    "id": 3,
    "name": "Rate Repository App",
    "image": "/../public/rateRepoApp.png",
    "description": "Multiplatform mobile app for rating GitHub repositories and finding new and popular repositories",
    "tags": ["react-native", "graphql", "expo", "apollo"],
    "source_code": "https://github.com/tylerFretz/rate-git-repository-app",
  },
  {
    "id": 4,
    "name": "Global News App",
    "image": "/../public/newsApp.gif",
    "description": "iOS mobile app built to consume The News API",
    "tags": ["swift", "uikit", "mapkit"],
    "source_code": "https://github.com/tylerFretz/mobile-news-app",
  },
  {
    "id": 5,
    "name": "VSCode Portfolio",
    "image": "/../public/portfolioApp.png",
    "description": "A themeable and developer-centric portfolio based on the VSCode",
    "tags": ["react", "typescript", "nextjs", "css-modules"],
    "source_code": "https://github.com/tylerFretz/tylerFretzPortfolio",
    "demo": "https://tylerfretzportfolio.vercel.app/",
  },
];